[project]
name = "calparse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "icalevents>=0.2.1",
]

[dependency-groups]
dev = [
    "ruff>=0.12.7",
]
