on:
  pull_request:
  push:
    branches:
      - main
      - release
jobs:
  test:
    runs-on: ubuntu-latest
    name: testing and linting this branch
    steps:
    - name: check out this repo
      uses: actions/checkout@v5
    - name: Install the latest version of uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"
    - name: lint frontend code
      run: |
        uv run ruff check
        uv run ruff format --check
    - name: check for TODO string instances
      run: |
        git ls-files | grep -v test-branch\.yml | xargs grep -Ii todo | wc -l | xargs ruby -e 'exit ARGV[0].to_i == 0'
    - name: check the basics work
      run: |
        echo '["https://calendar.google.com/calendar/ical/ht3jlfaac5lfd6263ulfh4tql8%40group.calendar.google.com/public/basic.ics"]' >urls.json
        uv run calparse.py list -f
        uv run calparse.py list
        uv run calparse.py random -f
        uv run calparse.py random
        rm -v "$HOME/.cache/calparse-cache.json"
        uv run calparse.py sequence -f
        uv run calparse.py sequence 
